# Задание 1 

Задайте матрицу А=$\left( \begin{matrix}
   3.25 & -1.07 & 2.34  \\
   10.1 & 0.25 & -4.78  \\
   5.04 & -7.79 & 3.31  \\
\end{matrix} \right)$


In [2]:
import numpy as np

A = np.array([
    [3.25, -1.07, 2.34],
    [10.1, 0.25, -4.78],
    [5.04, -7.79, 3.31],
], dtype=float)

A


array([[ 3.25, -1.07,  2.34],
       [10.1 ,  0.25, -4.78],
       [ 5.04, -7.79,  3.31]])

# Задание 2

Найти матрицу, обратную к A.

In [3]:
A_inv = np.linalg.inv(A)
A_inv


array([[ 0.14931587,  0.0602325 , -0.01857636],
       [ 0.23590453,  0.00424915, -0.16063614],
       [ 0.32783815, -0.08171327, -0.04765278]])

# Задание 3 

Сгенерируйте матрицу В размером 3х3 со случайными элементами, равномерно распределенными на интервале от 0 до 1. Выполнить операцию умножения матриц A и B, а затем транспонировать получившуюся матрицу.

In [ ]:
B = np.random.rand(3, 3)
(A @ B).T


array([[-0.0956581 , -0.1126552 , -4.38111585],
       [ 3.1567575 ,  8.56996961, -0.06609775],
       [ 2.28966596, -1.91179208,  0.70960415]])

# Задание 4

Нормализовать элементы заданного одномерного массива таким образом, чтобы значения лежали в диапазоне [0, 1].

In [17]:
x = np.array([1, 2, 11415, -531251, 4], dtype=float)
(x - x.min()) / (x.max() - x.min())



array([0.9789668 , 0.97896865, 1.        , 0.        , 0.97897233])

# Задание 5

Расположите элементы  матрицы А по возрастанию (по столбцам), определите максимальный и минимальный элементы  матрицы В, вычислите определитель матрицы В.

In [ ]:
np.sort(A, axis=0), B.min(), B.max(), np.linalg.det(B)


(array([[-1.07,  2.34,  3.25],
        [-4.78,  0.25, 10.1 ],
        [-7.79,  3.31,  5.04]]),
 np.float64(0.13455046571173057),
 np.float64(0.8897111630684411),
 np.float64(0.07830321332265891))

# Задание 6

Для двумерного массива размерностью 4×4 поменять местами первую строку и последнюю строки массива.

In [7]:
matr6 = np.arange(1, 17).reshape(4, 4)
matr6[[0, -1]] = matr6[[-1, 0]]

matr6


array([[13, 14, 15, 16],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

# Задание 7

Создать массив случайных вещественных чисел размером 5х5, используя функцию numpy.random.rand(). Затем вывести среднее значение элементов массива.

In [20]:
matr7 = np.random.rand(5, 5)

matr7.mean()


np.float64(0.5204421778607297)

# Задание 8

Задан вектор v длины 5. Рассчитайте евклидову норму этого вектора (также называемую L2-нормой).

In [21]:
v = np.array([1.5, -2.0, 3.0, 0.5, 4.0], dtype=float)
np.sqrt(np.sum(v**2)), np.linalg.norm(v)


(np.float64(5.612486080160912), np.float64(5.612486080160912))

# Задание 9

Создайте два массива одинаковой формы: первый состоит из четных чисел от 2 до 10, второй — из квадратов этих же чисел. Соедините оба массива горизонтально (по столбцам).

In [23]:
even_nums = np.arange(2, 11, 2)
squares = even_nums ** 2
np.hstack((even_nums.reshape(-1, 1), squares.reshape(-1, 1)))


array([[  2,   4],
       [  4,  16],
       [  6,  36],
       [  8,  64],
       [ 10, 100]])

# Задание 10

Задать массив С, используя операцию индексации и функцию ones:
$\left( \begin{matrix}
   1  \\
   1  \\
   -2.2  \\
   1   \\   
\end{matrix} \right)$

In [ ]:
C = np.ones(4)
C[2] = -2.2

C.reshape((4, 1))


array([[ 1. ],
       [ 1. ],
       [-2.2],
       [ 1. ]])

# Задание 11

Для двух векторов:
С и b= {0.6; 1.2; -1.8, 1.05} найти меру косинусного сходства.


In [40]:
b = np.array([0.6, 1.2, -1.8, 1.05], dtype=float).reshape(-1, 1)
cos_sim = (C.T @ b) / (np.linalg.norm(C) * np.linalg.norm(b))
cos_sim

array([0.98133321])