# Задание 1 

Задайте матрицу А=$\left( \begin{matrix}
   3.25 & -1.07 & 2.34  \\
   10.1 & 0.25 & -4.78  \\
   5.04 & -7.79 & 3.31  \\
\end{matrix} \right)$


In [43]:
import numpy as np

A = np.array([
    [3.25, -1.07, 2.34],
    [10.1, 0.25, -4.78],
    [5.04, -7.79, 3.31],
], dtype=float)

A


array([[ 3.25, -1.07,  2.34],
       [10.1 ,  0.25, -4.78],
       [ 5.04, -7.79,  3.31]])

# Задание 2

Найти матрицу, обратную к A.

In [44]:
A_inv = np.linalg.inv(A)
A_inv


array([[ 0.14931587,  0.0602325 , -0.01857636],
       [ 0.23590453,  0.00424915, -0.16063614],
       [ 0.32783815, -0.08171327, -0.04765278]])

# Задание 3 

Сгенерируйте матрицу В размером 3х3 со случайными элементами, равномерно распределенными на интервале от 0 до 1. Выполнить операцию умножения матриц A и B, а затем транспонировать получившуюся матрицу.

In [ ]:
rng = np.random.default_rng(67)
B = rng.random((3, 3))
(A @ B).T


array([[ 1.74993636,  2.7854122 ,  0.79316477],
       [ 0.60405365, -0.26675139, -2.8428934 ],
       [ 1.4161206 ,  4.87595739, -0.47612323]])

# Задание 4

Нормализовать элементы заданного одномерного массива таким образом, чтобы значения лежали в диапазоне [0, 1].

In [46]:
x = np.array([12, 5, 18, -3, 7], dtype=float)
x_normal = (x - x.min()) / (x.max() - x.min())

x_normal


array([0.71428571, 0.38095238, 1.        , 0.        , 0.47619048])

# Задание 5

Расположите элементы  матрицы А по возрастанию (по столбцам), определите максимальный и минимальный элементы  матрицы В, вычислите определитель матрицы В.

In [47]:
np.sort(A, axis=0), np.min(B), np.max(B), np.linalg.det(B)


(array([[ 3.25, -7.79, -4.78],
        [ 5.04, -1.07,  2.34],
        [10.1 ,  0.25,  3.31]]),
 np.float64(0.08851655047265261),
 np.float64(0.5980369520208466),
 np.float64(-0.06849946318682482))

# Задание 6

Для двумерного массива размерностью 4×4 поменять местами первую строку и последнюю строки массива.

In [48]:
matr6 = np.arange(1, 17).reshape(4, 4)
matr6[[0, -1]] = matr6[[-1, 0]]

matr6


array([[13, 14, 15, 16],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

# Задание 7

Создать массив случайных вещественных чисел размером 5х5, используя функцию numpy.random.rand(). Затем вывести среднее значение элементов массива.

In [49]:
matr7 = np.random.rand(5, 5)

np.mean(matr7)


np.float64(0.5159951319228473)

# Задание 8

Задан вектор v длины 5. Рассчитайте евклидову норму этого вектора (также называемую L2-нормой).

In [50]:
v = np.array([1.5, -2.0, 3.0, 0.5, 4.0], dtype=float)
np.linalg.norm(v, ord=2)


np.float64(5.612486080160912)

# Задание 9

Создайте два массива одинаковой формы: первый состоит из четных чисел от 2 до 10, второй — из квадратов этих же чисел. Соедините оба массива горизонтально (по столбцам).

In [51]:
even_nums = np.arange(2, 11, 2)
squares = even_nums ** 2
np.hstack((even_nums.reshape(-1, 1), squares.reshape(-1, 1)))


array([[  2,   4],
       [  4,  16],
       [  6,  36],
       [  8,  64],
       [ 10, 100]])

# Задание 10

Задать массив С, используя операцию индексации и функцию ones:
$\left( \begin{matrix}
   1  \\
   1  \\
   -2.2  \\
   1   \\   
\end{matrix} \right)$

In [52]:
C = np.ones((4, 1))
C[2, 0] = -2.2

C


array([[ 1. ],
       [ 1. ],
       [-2.2],
       [ 1. ]])

# Задание 11

Для двух векторов:
С и b= {0.6; 1.2; -1.8, 1.05} найти меру косинусного сходства.


In [53]:
b = np.array([0.6, 1.2, -1.8, 1.05], dtype=float).reshape(-1, 1)
cos_sim = (C.T @ b) / (np.linalg.norm(C) * np.linalg.norm(b))
cos_sim

array([[0.98133321]])