# Задание 1 

Задайте матрицу А=$\left( \begin{matrix}
   3.25 & -1.07 & 2.34  \\
   10.1 & 0.25 & -4.78  \\
   5.04 & -7.79 & 3.31  \\
\end{matrix} \right)$


In [ ]:
import numpy as np

A = np.array([
    [3.25, -1.07, 2.34],
    [10.1, 0.25, -4.78],
    [5.04, -7.79, 3.31],
])

A


array([[ 3.25, -1.07,  2.34],
       [10.1 ,  0.25, -4.78],
       [ 5.04, -7.79,  3.31]])

# Задание 2

Найти матрицу, обратную к A.

In [35]:
A_inv = np.linalg.inv(A)
A_inv


array([[ 0.14931587,  0.0602325 , -0.01857636],
       [ 0.23590453,  0.00424915, -0.16063614],
       [ 0.32783815, -0.08171327, -0.04765278]])

# Задание 3 

Сгенерируйте матрицу В размером 3х3 со случайными элементами, равномерно распределенными на интервале от 0 до 1. Выполнить операцию умножения матриц A и B, а затем транспонировать получившуюся матрицу.

In [36]:
B = np.random.rand(3, 3)
B, (A @ B).T


(array([[0.23974442, 0.17959419, 0.30372501],
        [0.86093008, 0.48078654, 0.49071337],
        [0.02865813, 0.15932297, 0.25741348]]),
 array([[-0.07496578,  2.49966534, -5.40347501],
        [ 0.44205527,  1.17253417, -2.31281338],
        [ 1.0643905 ,  1.95986446, -1.43984453]]))

# Задание 4

Нормализовать элементы заданного одномерного массива таким образом, чтобы значения лежали в диапазоне [0, 1].

In [37]:
x = np.array([1, 2, 11415, -531251, 4])
(x - x.min()) / (x.max() - x.min())



array([0.9789668 , 0.97896865, 1.        , 0.        , 0.97897233])

# Задание 5

Расположите элементы  матрицы А по возрастанию (по столбцам), определите максимальный и минимальный элементы  матрицы В, вычислите определитель матрицы В.

In [38]:
np.sort(A, axis=0), B.min(), B.max(), np.linalg.det(B)


(array([[ 3.25, -7.79, -4.78],
        [ 5.04, -1.07,  2.34],
        [10.1 ,  0.25,  3.31]]),
 np.float64(0.02865813273565887),
 np.float64(0.8609300814073156),
 np.float64(0.011128035814544045))

# Задание 6

Для двумерного массива размерностью 4×4 поменять местами первую строку и последнюю строки массива.

In [39]:
matr6 = np.arange(1, 17).reshape(4, 4)
matr6[[0, -1]] = matr6[[-1, 0]]

matr6


array([[13, 14, 15, 16],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

# Задание 7

Создать массив случайных вещественных чисел размером 5х5, используя функцию numpy.random.rand(). Затем вывести среднее значение элементов массива.

In [40]:
matr7 = np.random.rand(5, 5)

matr7.mean()


np.float64(0.4537762127367557)

# Задание 8

Задан вектор v длины 5. Рассчитайте евклидову норму этого вектора (также называемую L2-нормой).

In [41]:
v = np.array([1.5, -2.0, 3.0, 0.5, 4.0])
np.sqrt(np.sum(v**2)), np.linalg.norm(v)


(np.float64(5.612486080160912), np.float64(5.612486080160912))

# Задание 9

Создайте два массива одинаковой формы: первый состоит из четных чисел от 2 до 10, второй — из квадратов этих же чисел. Соедините оба массива горизонтально.

In [42]:
even_nums = np.arange(2, 11, 2)
np.hstack((even_nums, even_nums**2))


array([  2,   4,   6,   8,  10,   4,  16,  36,  64, 100])

# Задание 10

Задать массив С, используя операцию индексации и функцию ones:
$\left( \begin{matrix}
   1  \\
   1  \\
   -2.2  \\
   1   \\   
\end{matrix} \right)$

In [43]:
C = np.ones(4)
C[2] = -2.2

C.reshape((4, 1))


array([[ 1. ],
       [ 1. ],
       [-2.2],
       [ 1. ]])

# Задание 11

Для двух векторов:
С и b= {0.6; 1.2; -1.8, 1.05} найти меру косинусного сходства.


In [44]:
b = np.array([0.6, 1.2, -1.8, 1.05]).reshape(-1, 1)
cos_sim = (C.T @ b) / (np.linalg.norm(C) * np.linalg.norm(b))
cos_sim

array([0.98133321])